### PR TITLE
fix east asian width char alignment

### LINKED ISSUE #5: imperfect alignment due to Asian language
The alignment has bug if text contains Asian language word like Japanese or Chinese.

```
ヒトリエ            ███████████████████████░░░░     75 plays
Polyphia        ████████████████░░░░░░░░░░░     50 plays
CHON            █████████████░░░░░░░░░░░░░░     43 plays
草東沒有派對          ██████░░░░░░░░░░░░░░░░░░░░░     18 plays
amazarashi      █████░░░░░░░░░░░░░░░░░░░░░░     16 plays
```

Sorry that I'm not a programmer so not able to handle this, hope you can fix it.

### PR DESCRIPTION
**Pull request by casperdcl**
- fixes #5 using [komagata/eastasianwidth](https://github.com/komagata/eastasianwidth)

### CODE REVIEW

**Comment by casperdcl** [comment]
@Boycottangent let me know if this works for you

**Comment by Boycottangent** [comment]
circleci shows error
```
#!/bin/bash -eo pipefail
node index.js
music-box ran into an issue getting your Gist:
HttpError: Bad credentials
Unable to update gist
TypeError: Cannot read property 'data' of undefined
```
What's the problem?

BTW, I wonder if I can use the Github Action instead of circleci

**Comment by Boycottangent** [comment]
it seems that the alignment bug still exists 😕
https://gist.github.com/Boycottangent/cc94ef872818a4adbad324d0bb229082

**Comment by casperdcl** [comment]
Are you sure you're using this PR? Your fork looks like it's based off of [jacc:master](https://github.com/jacc/music-box) rather than [casperdcl:eaw](https://github.com/casperdcl/music-box/tree/eaw)

**Comment by casperdcl** [comment]
@Boycottangent just fixed it and actually tested with the artists in your gist. Should work now if you rebase on [casperdcl:eaw](https://github.com/casperdcl/music-box/tree/eaw)

**Comment by Boycottangent** [comment]
I manually merged these change(replacing `index.js`, `package.json` and `package-lock.json` from  [casperdcl:eaw](https://github.com/casperdcl/music-box/tree/eaw) but doesn't work

**Comment by casperdcl** [comment]
@Boycottangent ah but it looks less bad (some spaces were removed). Still looks like even more spacing needs to be removed. Odd because in my terminal it looks right.

copy-pasting this:
```
ヒトリエ                   ██████▋░░░░░░░░░░    70 plays
CHON                       ██░░░░░░░░░░░░░░░    22 plays
```
in my terminal I get:
image

I think this is now a GitHub fonts issue.

@jacc I think this PR should be merged and possibly a ticket opened with GitHub about fonts.

**Comment by Boycottangent** [comment]
yeah, looks more acceptable. Thanks 👍

**Comment by jacc** [comment]
thank you @casperdcl for the fix and @Boycottangent for testing :)

**Comment by hezhizhen** [comment]
> 

I have the same problem here: https://gist.github.com/hezhizhen/ad7aaf14b14bd70b0143cbcc887327ab . In my terminal they are aligned.

**Pull request merged**
